{"name": "test_case5", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <Testcases.testLoginCase.TestLoginCase object at 0x7fa660cdd978>\n\n    @allure.step(title=\"登录用例5\")\n    def test_case5(self):\n        status=getCaseStatus(os.getcwd()+\"/data/testcase.xlsx\", \"清单测试用例\", 5)\n>       assert False\nE       assert False\n\n/home/autoProject/APIAutomation/Testcases/testLoginCase.py:30: AssertionError"}, "steps": [{"name": "登录用例5", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n", "trace": "  File \"/usr/local/lib/python3.6/site-packages/allure_commons/_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"/home/autoProject/APIAutomation/Testcases/testLoginCase.py\", line 30, in test_case5\n    assert False\n"}, "start": 1589362005732, "stop": 1589362005735}], "start": 1589362005732, "stop": 1589362005797, "uuid": "2d8f8829-5d53-4d23-9fdf-16afeef98e5b", "historyId": "41bd9d5a6a69b72cb2e1bc18ad1cf064", "testCaseId": "4ce3b2c6f07757d45c6d68ee857e5079", "fullName": "Testcases.testLoginCase.TestLoginCase#test_case5", "labels": [{"name": "parentSuite", "value": "Testcases"}, {"name": "suite", "value": "testLoginCase"}, {"name": "subSuite", "value": "TestLoginCase"}, {"name": "host", "value": "localhost.localdomain"}, {"name": "thread", "value": "3902-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Testcases.testLoginCase"}]}